[2025-04-30T20:24:08.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bixi_main_dag.nettoyage_et_sauvegarde_csv manual__2025-04-30T20:24:07.063741+00:00 [queued]>
[2025-04-30T20:24:08.163+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bixi_main_dag.nettoyage_et_sauvegarde_csv manual__2025-04-30T20:24:07.063741+00:00 [queued]>
[2025-04-30T20:24:08.163+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-30T20:24:08.168+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): nettoyage_et_sauvegarde_csv> on 2025-04-30 20:24:07.063741+00:00
[2025-04-30T20:24:08.171+0000] {standard_task_runner.py:60} INFO - Started process 201 to run task
[2025-04-30T20:24:08.174+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'bixi_main_dag', 'nettoyage_et_sauvegarde_csv', 'manual__2025-04-30T20:24:07.063741+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/bixi_main_dag.py', '--cfg-path', '/tmp/tmpo6yr0azn']
[2025-04-30T20:24:08.175+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask nettoyage_et_sauvegarde_csv
[2025-04-30T20:24:08.186+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-30T20:24:08.211+0000] {task_command.py:423} INFO - Running <TaskInstance: bixi_main_dag.nettoyage_et_sauvegarde_csv manual__2025-04-30T20:24:07.063741+00:00 [running]> on host d5f0c6aea8de
[2025-04-30T20:24:08.253+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bixi_main_dag' AIRFLOW_CTX_TASK_ID='nettoyage_et_sauvegarde_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T20:24:07.063741+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T20:24:07.063741+00:00'
[2025-04-30T20:24:08.387+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bixi_main_dag.py", line 17, in nettoyer_et_sauvegarder
    df = pd.read_csv("/opt/airflow/data/bixi_trips.csv")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/bixi_trips.csv'
[2025-04-30T20:24:08.392+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bixi_main_dag, task_id=nettoyage_et_sauvegarde_csv, execution_date=20250430T202407, start_date=20250430T202408, end_date=20250430T202408
[2025-04-30T20:24:08.397+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task nettoyage_et_sauvegarde_csv ([Errno 2] No such file or directory: '/opt/airflow/data/bixi_trips.csv'; 201)
[2025-04-30T20:24:08.435+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T20:24:08.444+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
